### ISSUE TITLE
Multiple ISO Direction Render

### ISSUE THREAD

**Issue by Morketh** [webbukkit/DynmapForge#50]
i was looking around in the config files for some clarification on rendering a map using different orientations i only found the Old North settings. Is there a way to render a map from multiple Isometric views?

**Comment by Morketh** [comment]
ANSWER: Yes there is!!
20 days later and i figured it out.
ill post the configuration settings for others to see in a Gist

**Comment by Morketh** [comment]
Ok so here it is all you need to do is add multiple Perspectives (such as the ones listed below) to the ```custom-normal-hires.txt``` file under the template directory.
```yaml
      - class: org.dynmap.hdmap.HDMap
        name: surface_se
        title: "Surface SE"
        prefix: tse
        perspective: iso_SE_30_hires
        shader: lbp_shade
        lighting: shadows
        mapzoomin: 1
      - class: org.dynmap.hdmap.HDMap
        name: surface_nw
        title: "Surface NW"
        prefix: tnw
        perspective: iso_NW_30_hires
        shader: lbp_shade
        lighting: shadows
        mapzoomin: 1
```
